### ISSUE TITLE
Latest rr release doesn't support Zen 4

### ISSUE THREAD

**Issue by pepijndevos** [JuliaLang/BugReporting.jl#108]
On my computer I get
```
[FATAL src/PerfCounters_x86.h:114:compute_cpu_microarch()] AMD CPU type 0x60f10 (ext family 0xa) unknown
```
when running `julia --bug-report=rr` and I have confirmed that using the latest rr standalone fixes the problem.

**Comment by giordano** [comment]
Lastest `rr_jll` is [v5.6.0](https://github.com/JuliaBinaryWrappers/rr_jll.jl/releases/tag/rr-v5.6.0%2B0), and unless I'm missing something latest rr stable version is also [v5.6.0](https://github.com/rr-debugger/rr/releases/tag/5.6.0)?

**Comment by DilumAluthge** [comment]
The version number in rr_jll might be misleading. We build rr_jll from a branch in Keno's fork. I'm guessing we probably need to rebase that branch against upstream so that we can pick up some recent fixes made in upstream.

**Comment by giordano** [comment]
Did you check the history of https://github.com/JuliaLang/rr/commits/392a88abb35922abdcf73eaf1e21a1980f766762 (and https://github.com/JuliaLang/rr/commit/392a88abb35922abdcf73eaf1e21a1980f766762 is the revision mentioned by https://github.com/JuliaPackaging/Yggdrasil/blob/5e513decf6e973492165a302a8ae2c7b6408fa1a/R/rr/build_tarballs.jl#L11)?

**Comment by DilumAluthge** [comment]
Aha good call.

The last common commit between our fork and upstream is https://github.com/JuliaLang/rr/commit/069ace052af3aedc134015712519468140a90b30 in our fork and https://github.com/rr-debugger/rr/commit/069ace052af3aedc134015712519468140a90b30 in upstream.

Based on that, our fork is missing the https://github.com/rr-debugger/rr/commit/140d3cfcda939a11aae828bfa3a5331ca9a4e287 commit from upstream.

Looking at https://github.com/rr-debugger/rr/commit/140d3cfcda939a11aae828bfa3a5331ca9a4e287, that commit adds: `case 0x60f10: // Raphael (Zen 4)`.

And `0x60f10` is exactly what is reported in the error message in the OP.

**Comment by giordano** [comment]
Yeah, but that commit is _after_ the latest stable version, so I wouldn't say the JLL build is _that_ old :grinning:  But it's still too old for @pepijndevos.

**Comment by maleadt** [comment]
Seems simple enough to backport on top of our fork. I'll have a look.
