### ISSUE TITLE
Check `/proc/sys/kernel/perf_event_paranoid` before starting `rr`?

### ISSUE THREAD

**Issue by tkf** [JuliaLang/BugReporting.jl#21]
I often forget running `sudo sysctl kernel.perf_event_paranoid=1` before starting the bug-report session and get

```
[ Info: Loading BugReporting package...
rr needs /proc/sys/kernel/perf_event_paranoid <= 1, but it is 2.
Change it to 1, or use 'rr record -n' (slow).
Consider putting 'kernel.perf_event_paranoid = 1' in /etc/sysctl.conf
[ Info: Preparing trace directory for upload (if your trace is large this may take a few minutes)
...
```

The error message from `rr` is a bit hard see when it's followed by other message from BugReporting.jl since BugReporting.jl will try to upload the empty trace directory.

Maybe it makes sense to check `/proc/sys/kernel/perf_event_paranoid` before starting `rr`?

**Comment by Keno** [comment]
Sounds like a good idea.
