### ISSUE TITLE
A way to retrieve source code for a given Julia version

### ISSUE THREAD

**Issue by Keno** [JuliaLang/BugReporting.jl#23]
The trace contains references to the julia version that built it. It should be easy for us to automatically get a checkout of the source that we can point GDB to.

**Comment by maleadt** [comment]
> The trace contains references to the julia version that built it.

Where exactly? `version_sh.git` only generates Julia code, and I guess we'd need to continue past initialization to safely be able to access that info (which we probably don't want to do).
