### ISSUE TITLE
–bug-report=rr doesn’t play nicely with hang & interrupt

### ISSUE THREAD

**Issue by christopherdavidwhite** [JuliaLang/BugReporting.jl#38]
I’m trying to construct and submit an rr bug report for semi-heisenbug (possibly in Julia itself). When I run

    julia my-script.jl

(julia 1.6.1), I get one of a variety of errors, e.g.

    corrupted double-linked list

or

    julia: malloc.c:3848: _int_malloc: Assertion `chunk_main_arena (fwd)' failed.

    signal (6): Aborted

and the program hangs. (Via debugging println()s I know that it's hanging at a function call: the println immediately before the function call prints, while the println in the first line of the function body does _not_.) I then send an interrupt with Ctrl-c.

The problem is, this interrupt—which is necessary to get the program to end!—interrupts the creation of the rr recording, so I have nothing to send in.

This seems like the perfect case for `rr`: some kind of memory weirdness at a function call boundary. How can I create the bug report?

(FWIW this is a lightly edited version of my Discourse question https://discourse.julialang.org/t/bug-report-rr-doesnt-play-nicely-with-hang-interrupt-how-to-create-bug-report/60718 . Not sure that was the right place to ask, and since this really does seem somewhere between a bug report and a feature request, I thought it'd be worth trying here.)

**Comment by christopherdavidwhite** [comment]
OK, so going through the source I found that the environment variable `JULIA_RR_IGNORE_STATUS` ought to do what I want: see https://github.com/JuliaLang/BugReporting.jl/blob/dfaad7dd45f68ffbb3830ba4fa351cb33e97b4f1/src/BugReporting.jl#L186 and https://github.com/JuliaLang/BugReporting.jl/blob/dfaad7dd45f68ffbb3830ba4fa351cb33e97b4f1/src/BugReporting.jl#L335 --- but interrupt still prevents the rr bug-report generation from running to completion.

**Comment by maleadt** [comment]
The problem is that the SIGINT is caught by the parent process that calls `rr julia`, and not the child.
