### ISSUE TITLE
Vendored libstdc++ breaks replay

### ISSUE THREAD

**Issue by maleadt** [JuliaLang/BugReporting.jl#46]
If I use BugReporting.replay to try and replay a trace, I'm getting:

```
julia> replay("https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/rr/Example-1658164614.tar.zst")
gdb: /home/tim/Julia/depot/juliaup/julia-1.7.3+0~x64/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by gdb)
gdb: /home/tim/Julia/depot/juliaup/julia-1.7.3+0~x64/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libsource-highlight.so.4)
gdb: /home/tim/Julia/depot/juliaup/julia-1.7.3+0~x64/bin/../lib/julia/libcurl.so.4: no version information available (required by /usr/lib/libdebuginfod.so.1)
gdb: /home/tim/Julia/depot/juliaup/julia-1.7.3+0~x64/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib/libboost_regex.so.1.79.0)
```

If however I download the tarball myself and use my local `rr replay`, everything works fine. I guess the packaged (older) glibc is somehow messing things up? This is probably also related to me using Arch, which ships a very recent glibc.

**Comment by Keno** [comment]
Try adding `--serve-files` to the rr replay line. That's generally required when moving traces across machines.

**Comment by giordano** [comment]
Spamming also here that help on Windows for https://github.com/JuliaLang/julia/pull/45582 would be great, and solve these issues (at least until next year) :upside_down_face:

**Comment by maleadt** [comment]
> Try adding `--serve-files` to the rr replay line. That's generally required when moving traces across machines.

Sadly, doesn't help:

```
julia> replay("https://s3.amazonaws.com/julialang-reports/nanosoldier/pkgeval/rr/Example-1658164614.tar.zst")
`$(rr_path) replay --serve-files $(find_latest_trace(trace_url))` = `/home/tim/Julia/depot/artifacts/d09d37c8f9642702eb9430cde245b189a0f5b28c/bin/rr replay --serve-files /home/tim/Julia/depot/artifacts/cab573584c24012493dcea86cffc83ad9c0b26b7`
gdb: /home/tim/Julia/depot/juliaup/julia-1.8.0-rc1+0~x64/bin/../lib/julia/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by gdb)
```

**Comment by Keno** [comment]
Oh, I see, the issue is not the vendored libstdc++ inside the trace, but that having libstdc++ in the julia distribution causes gdb to load the wrong libstdc++. We could probably consider using Gdb_jll here rather than relying on whatever gdb you have installed.
